### ISSUE TITLE
Documentation for font weights is not valid

### ISSUE THREAD

**Issue by fatherOfLegends** [eBay/flutter_glove_box#133]
> Caveats
Unfortunately, Flutter's font loading support for testing is fairly limited.
At the moment, it is only possible to load a single .ttf file for a font family. This means it may not be possible to get the proper visuals to appear. For example, different font weights may not work

Different font weights do work with this package as long as the font weights are properly configured. Flutter requires different font files to be assigned to different weights. As long as each font file has a unique name the fonts display properly.

```
flutter:
  fonts:
    - family: LibreBaskerville
      fonts:
        - asset: fonts/LibreBaskerville-Regular.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
```

Here is an example of a golden with these fonts and weights:

![image](https://user-images.githubusercontent.com/1594695/147292931-40ce3f6b-8f71-4095-849c-57a1885d0961.png)
